### ISSUE TITLE
Wrong view model after weapon switch

### ISSUE THREAD

**Issue by maikmerten** [OldTimes-Software/KatanaEngine#101]
In rare instances switching weapons does not appear to swap out the weapon model correctly.
![0005](https://cloud.githubusercontent.com/assets/2611432/5762188/b921029c-9ce0-11e4-948c-560f54cf81d4.jpg)

**Comment by hogsy** [comment]
I shall deal with this as soon as I'm done with the engine :+1:

**Comment by hogsy** [comment]
Did a quick check over everything and this is most likely down to weapon cycling being incomplete, so I shall close it for now and then we can review this issue again if it props up again.
