### ISSUE TITLE
Level: Override or extend list of WAD files of map files via commandline option

### ISSUE THREAD

**Issue by maikmerten** [OldTimes-Software/KatanaEngine#107]
The .map files exported by Jackhammer contain absolute paths that are unlikely to work across machines. This will make it difficult to set up a batch compile solution when assembling releases.

Level should have an option to override or extend the WAD files declaration given in the .map file. It appears that Level has provisions for a "-wadpath" commandline option, but it is not documented and rejected as unknown option when specified.

**Comment by hogsy** [comment]
-wadpath has been added but only accepts one given path for now.
