### ISSUE TITLE
Decide on player dimensions

### ISSUE THREAD

**Issue by maikmerten** [OldTimes-Software/KatanaEngine#108]
Changes regarding player size, view height and crouching dimensions impact gamecode, the engine and the map compiler (hulls!). So if we want something different from Quake this needs to be decided and implemented wherever it matters.

**Comment by maikmerten** [comment]
Something interesting regarding Quake's and Half-Life's dimensions:

http://forums.inside3d.com/viewtopic.php?p=26193&sid=2da61a155a18e2a4519e0d07ea53d5db#p26193

Developer information by Valve: https://developer.valvesoftware.com/wiki/Dimensions#Player_Collision_Hull

**Comment by hogsy** [comment]
I think we've all agreed that the player should be about the same size that the player is in Half-Life, so I shall see to implementing that as soon as I can.
