### ISSUE TITLE
Player movement: Ice-skating (no friction)

### ISSUE THREAD

**Issue by maikmerten** [OldTimes-Software/KatanaEngine#128]
Currently the player does not seem to encounter friction - when releasing +forward the player will happily slide on until he is stopped by wall.

How to reproduce: load sewer-a, press +forward, release +forward, enjoy your ride

**Comment by hogsy** [comment]
Any other steps to this? So far I've been unable to replicate it.

**Comment by maikmerten** [comment]
Hmmm... I do not need additional steps, this issue is very "reliable" for me. Perhaps a Linux/GCC floating-point thing. I will retest and report back.

**Comment by hogsy** [comment]
Is this still a problem or has it been resolved now?

**Comment by maikmerten** [comment]
Did not encounter this problem last time I checked. Close for now, can be reopened if necessary later on.
