### ISSUE TITLE
level: directional lights find other entities by "targetname", not "name"

### ISSUE THREAD

**Issue by maikmerten** [OldTimes-Software/KatanaEngine#144]
Directional lights need to target another entity. In the editor, entities are named by the "name" attribute. However, level expects to find the entities by "targetname".

Level should search for "name". Given that we already have maps that use "targetname" for directional lights the tool should also search for "targetname" if the first search yields no results.

**Comment by hogsy** [comment]
Isn't this standard behaviour for Quake? Regardless I've changed it for you and have also managed (as far as I'm aware) to track down the issue with the lighting in the Level tool.

I'll close this task once it's tested.

**Comment by maikmerten** [comment]
Yeah, locating entities by "targetname" is standard for Quake, but our mapping setup seems to be inspired by Half-Life, where "name" is the proper attribute name.

**Comment by hogsy** [comment]
This is done and up now!
