### ISSUE TITLE
Implement crouching.

### ISSUE THREAD

**Issue by hogsy** [OldTimes-Software/KatanaEngine#62]
Allow the player to crouch, causing their hull to shrink.

**Comment by maikmerten** [comment]
This will need a modification to both the map compiler and the engine to support a crouching hull - but according to 

http://forums.inside3d.com/viewtopic.php?f=3&t=2641&sid=0ea9d8cff26c779f6226036aa9a28959&start=15

the Quake .bsp format already supports four hulls, of which one is unused - so no new .bsp format should be needed.

This explains
```
void CreateHulls (void)
{
...
  hullinfo.numhulls	= 3;
  hullinfo.filehulls	= BSP_MAX_HULLS;
...
}
```

in the map compiler (BSP_MAX_HULLS is defined as 4).

**Comment by hogsy** [comment]
It's a short-term solution though, I think it would be better to implement something more long-term. In the mean time I suppose I could still implement it as a temporary solution.
